// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserDesignationEnum string

const (
	UserDesignationEnumNishajAdmin UserDesignationEnum = "nishaj_admin"
	UserDesignationEnumAuditor     UserDesignationEnum = "auditor"
	UserDesignationEnumTeamMember  UserDesignationEnum = "team_member"
	UserDesignationEnumPocInternal UserDesignationEnum = "poc_internal"
	UserDesignationEnumPocClient   UserDesignationEnum = "poc_client"
	UserDesignationEnumStakeholder UserDesignationEnum = "stakeholder"
)

func (e *UserDesignationEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserDesignationEnum(s)
	case string:
		*e = UserDesignationEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UserDesignationEnum: %T", src)
	}
	return nil
}

type NullUserDesignationEnum struct {
	UserDesignationEnum UserDesignationEnum `json:"user_designation_enum"`
	Valid               bool                `json:"valid"` // Valid is true if UserDesignationEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserDesignationEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UserDesignationEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserDesignationEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserDesignationEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserDesignationEnum), nil
}

func (e UserDesignationEnum) Valid() bool {
	switch e {
	case UserDesignationEnumNishajAdmin,
		UserDesignationEnumAuditor,
		UserDesignationEnumTeamMember,
		UserDesignationEnumPocInternal,
		UserDesignationEnumPocClient,
		UserDesignationEnumStakeholder:
		return true
	}
	return false
}

func AllUserDesignationEnumValues() []UserDesignationEnum {
	return []UserDesignationEnum{
		UserDesignationEnumNishajAdmin,
		UserDesignationEnumAuditor,
		UserDesignationEnumTeamMember,
		UserDesignationEnumPocInternal,
		UserDesignationEnumPocClient,
		UserDesignationEnumStakeholder,
	}
}

type Client struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	EmailDomain *string   `json:"email_domain"`
}

type User struct {
	ID           uuid.UUID           `json:"id"`
	Email        string              `json:"email"`
	Name         string              `json:"name"`
	OidcProvider string              `json:"oidc_provider"`
	OidcSub      string              `json:"oidc_sub"`
	Designation  UserDesignationEnum `json:"designation"`
	ClientID     pgtype.UUID         `json:"client_id"`
	CreatedAt    pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz  `json:"updated_at"`
	LastLogin    pgtype.Timestamptz  `json:"last_login"`
}
