// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserRoleEnum string

const (
	UserRoleEnumNishajAdmin UserRoleEnum = "nishaj_admin"
	UserRoleEnumAuditor     UserRoleEnum = "auditor"
	UserRoleEnumTeamMember  UserRoleEnum = "team_member"
	UserRoleEnumPocInternal UserRoleEnum = "poc_internal"
	UserRoleEnumPocClient   UserRoleEnum = "poc_client"
	UserRoleEnumStakeholder UserRoleEnum = "stakeholder"
)

func (e *UserRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoleEnum(s)
	case string:
		*e = UserRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoleEnum: %T", src)
	}
	return nil
}

type NullUserRoleEnum struct {
	UserRoleEnum UserRoleEnum `json:"user_role_enum"`
	Valid        bool         `json:"valid"` // Valid is true if UserRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoleEnum), nil
}

func (e UserRoleEnum) Valid() bool {
	switch e {
	case UserRoleEnumNishajAdmin,
		UserRoleEnumAuditor,
		UserRoleEnumTeamMember,
		UserRoleEnumPocInternal,
		UserRoleEnumPocClient,
		UserRoleEnumStakeholder:
		return true
	}
	return false
}

func AllUserRoleEnumValues() []UserRoleEnum {
	return []UserRoleEnum{
		UserRoleEnumNishajAdmin,
		UserRoleEnumAuditor,
		UserRoleEnumTeamMember,
		UserRoleEnumPocInternal,
		UserRoleEnumPocClient,
		UserRoleEnumStakeholder,
	}
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	OidcProvider string             `json:"oidc_provider"`
	OidcSub      string             `json:"oidc_sub"`
	Role         UserRoleEnum       `json:"role"`
	ClientID     pgtype.UUID        `json:"client_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
}
