// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (email, name, oidc_provider, oidc_sub, designation, client_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, name, designation, client_id, created_at, updated_at, last_login
`

type CreateUserParams struct {
	Email        string              `json:"email"`
	Name         string              `json:"name"`
	OidcProvider string              `json:"oidc_provider"`
	OidcSub      string              `json:"oidc_sub"`
	Designation  UserDesignationEnum `json:"designation"`
	ClientID     pgtype.UUID         `json:"client_id"`
}

type CreateUserRow struct {
	ID          uuid.UUID           `json:"id"`
	Email       string              `json:"email"`
	Name        string              `json:"name"`
	Designation UserDesignationEnum `json:"designation"`
	ClientID    pgtype.UUID         `json:"client_id"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `json:"updated_at"`
	LastLogin   pgtype.Timestamptz  `json:"last_login"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.Email,
		arg.Name,
		arg.OidcProvider,
		arg.OidcSub,
		arg.Designation,
		arg.ClientID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Designation,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteUser, id)
	return err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, designation, client_id, created_at, updated_at, last_login
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID          uuid.UUID           `json:"id"`
	Email       string              `json:"email"`
	Name        string              `json:"name"`
	Designation UserDesignationEnum `json:"designation"`
	ClientID    pgtype.UUID         `json:"client_id"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `json:"updated_at"`
	LastLogin   pgtype.Timestamptz  `json:"last_login"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Designation,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, email, name, designation, client_id, created_at, updated_at, last_login
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID          uuid.UUID           `json:"id"`
	Email       string              `json:"email"`
	Name        string              `json:"name"`
	Designation UserDesignationEnum `json:"designation"`
	ClientID    pgtype.UUID         `json:"client_id"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `json:"updated_at"`
	LastLogin   pgtype.Timestamptz  `json:"last_login"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, GetUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Designation,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const GetUserByOIDC = `-- name: GetUserByOIDC :one
SELECT id, email, name, designation, client_id, created_at, updated_at, last_login
FROM users
WHERE oidc_provider = $1 AND oidc_sub = $2
LIMIT 1
`

type GetUserByOIDCParams struct {
	OidcProvider string `json:"oidc_provider"`
	OidcSub      string `json:"oidc_sub"`
}

type GetUserByOIDCRow struct {
	ID          uuid.UUID           `json:"id"`
	Email       string              `json:"email"`
	Name        string              `json:"name"`
	Designation UserDesignationEnum `json:"designation"`
	ClientID    pgtype.UUID         `json:"client_id"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `json:"updated_at"`
	LastLogin   pgtype.Timestamptz  `json:"last_login"`
}

func (q *Queries) GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (GetUserByOIDCRow, error) {
	row := q.db.QueryRow(ctx, GetUserByOIDC, arg.OidcProvider, arg.OidcSub)
	var i GetUserByOIDCRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Designation,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, email, name, designation, client_id, created_at, updated_at, last_login
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID          uuid.UUID           `json:"id"`
	Email       string              `json:"email"`
	Name        string              `json:"name"`
	Designation UserDesignationEnum `json:"designation"`
	ClientID    pgtype.UUID         `json:"client_id"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `json:"updated_at"`
	LastLogin   pgtype.Timestamptz  `json:"last_login"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, ListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Designation,
			&i.ClientID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, email = $3, designation = $4
WHERE id = $1
RETURNING id, email, name, designation, client_id, created_at, updated_at, last_login
`

type UpdateUserParams struct {
	ID          uuid.UUID           `json:"id"`
	Name        string              `json:"name"`
	Email       string              `json:"email"`
	Designation UserDesignationEnum `json:"designation"`
}

type UpdateUserRow struct {
	ID          uuid.UUID           `json:"id"`
	Email       string              `json:"email"`
	Name        string              `json:"name"`
	Designation UserDesignationEnum `json:"designation"`
	ClientID    pgtype.UUID         `json:"client_id"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `json:"updated_at"`
	LastLogin   pgtype.Timestamptz  `json:"last_login"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, UpdateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Designation,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Designation,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const UpdateUserClientID = `-- name: UpdateUserClientID :exec
UPDATE users
SET client_id = $2
WHERE id = $1
`

type UpdateUserClientIDParams struct {
	ID       uuid.UUID   `json:"id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) UpdateUserClientID(ctx context.Context, arg UpdateUserClientIDParams) error {
	_, err := q.db.Exec(ctx, UpdateUserClientID, arg.ID, arg.ClientID)
	return err
}

const UpdateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, UpdateUserLastLogin, id)
	return err
}
