// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkCreateFrameworkQuestions implements pgx.CopyFromSource.
type iteratorForBulkCreateFrameworkQuestions struct {
	rows                 []BulkCreateFrameworkQuestionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateFrameworkQuestions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateFrameworkQuestions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FrameworkID,
		r.rows[0].ControlID,
		r.rows[0].QuestionText,
		r.rows[0].HelpText,
		r.rows[0].AcceptableEvidence,
	}, nil
}

func (r iteratorForBulkCreateFrameworkQuestions) Err() error {
	return nil
}

func (q *Queries) BulkCreateFrameworkQuestions(ctx context.Context, arg []BulkCreateFrameworkQuestionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"framework_questions"}, []string{"framework_id", "control_id", "question_text", "help_text", "acceptable_evidence"}, &iteratorForBulkCreateFrameworkQuestions{rows: arg})
}
