// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ComplianceFramework struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Description   *string            `json:"description"`
	ChecklistJson []byte             `json:"checklist_json"`
	Version       *string            `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type FrameworkQuestion struct {
	QuestionID         uuid.UUID          `json:"question_id"`
	FrameworkID        uuid.UUID          `json:"framework_id"`
	ControlID          string             `json:"control_id"`
	QuestionText       string             `json:"question_text"`
	HelpText           *string            `json:"help_text"`
	AcceptableEvidence []string           `json:"acceptable_evidence"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SectionTitle       *string            `json:"section_title"`
}
