// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BulkCreateFrameworkQuestions(ctx context.Context, arg []BulkCreateFrameworkQuestionsParams) (int64, error)
	CountFrameworkQuestions(ctx context.Context, frameworkID uuid.UUID) (int64, error)
	CountFrameworks(ctx context.Context) (int64, error)
	CreateFramework(ctx context.Context, arg CreateFrameworkParams) (CreateFrameworkRow, error)
	CreateFrameworkQuestion(ctx context.Context, arg CreateFrameworkQuestionParams) (FrameworkQuestion, error)
	DeleteFramework(ctx context.Context, id uuid.UUID) error
	DeleteFrameworkQuestion(ctx context.Context, questionID uuid.UUID) error
	DeleteFrameworkQuestionsByFrameworkId(ctx context.Context, frameworkID uuid.UUID) error
	GetFramework(ctx context.Context, id uuid.UUID) (ComplianceFramework, error)
	GetFrameworkByName(ctx context.Context, name string) (ComplianceFramework, error)
	GetFrameworkQuestion(ctx context.Context, questionID uuid.UUID) (FrameworkQuestion, error)
	GetFrameworkWithQuestions(ctx context.Context, id uuid.UUID) ([]GetFrameworkWithQuestionsRow, error)
	ListFrameworkQuestions(ctx context.Context, frameworkID uuid.UUID) ([]FrameworkQuestion, error)
	ListFrameworks(ctx context.Context) ([]ComplianceFramework, error)
	UpdateFramework(ctx context.Context, arg UpdateFrameworkParams) (ComplianceFramework, error)
	UpdateFrameworkQuestion(ctx context.Context, arg UpdateFrameworkQuestionParams) (FrameworkQuestion, error)
}

var _ Querier = (*Queries)(nil)
