// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_log.sql

package clientdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_log (
    user_id,
    user_email,
    action,
    entity_type,
    entity_id,
    details,
    ip_address,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, user_email, action, entity_type, entity_id, details, ip_address, user_agent, created_at
`

type CreateActivityLogParams struct {
	UserID     uuid.UUID `json:"user_id"`
	UserEmail  string    `json:"user_email"`
	Action     string    `json:"action"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Details    []byte    `json:"details"`
	IpAddress  *string   `json:"ip_address"`
	UserAgent  *string   `json:"user_agent"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, CreateActivityLog,
		arg.UserID,
		arg.UserEmail,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserEmail,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteOldActivityLogs = `-- name: DeleteOldActivityLogs :exec
DELETE FROM activity_log
WHERE created_at < $1
`

func (q *Queries) DeleteOldActivityLogs(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, DeleteOldActivityLogs, createdAt)
	return err
}

const GetRecentActivity = `-- name: GetRecentActivity :many
SELECT id, user_id, user_email, action, entity_type, entity_id, details, ip_address, user_agent, created_at FROM activity_log
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetRecentActivity(ctx context.Context, limit int32) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, GetRecentActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListActivityLogs = `-- name: ListActivityLogs :many
SELECT id, user_id, user_email, action, entity_type, entity_id, details, ip_address, user_agent, created_at FROM activity_log
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActivityLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, ListActivityLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListActivityLogsByAction = `-- name: ListActivityLogsByAction :many
SELECT id, user_id, user_email, action, entity_type, entity_id, details, ip_address, user_agent, created_at FROM activity_log
WHERE action = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityLogsByActionParams struct {
	Action string `json:"action"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListActivityLogsByAction(ctx context.Context, arg ListActivityLogsByActionParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, ListActivityLogsByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListActivityLogsByEntity = `-- name: ListActivityLogsByEntity :many
SELECT id, user_id, user_email, action, entity_type, entity_id, details, ip_address, user_agent, created_at FROM activity_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type ListActivityLogsByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) ListActivityLogsByEntity(ctx context.Context, arg ListActivityLogsByEntityParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, ListActivityLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListActivityLogsByUser = `-- name: ListActivityLogsByUser :many
SELECT id, user_id, user_email, action, entity_type, entity_id, details, ip_address, user_agent, created_at FROM activity_log
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityLogsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, ListActivityLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
