// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package clientdb

import (
	"context"

	"github.com/google/uuid"
)

const CreateComment = `-- name: CreateComment :one
INSERT INTO comments (
    submission_id,
    user_id,
    user_name,
    comment_text,
    is_internal
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, submission_id, user_id, user_name, comment_text, is_internal, created_at, updated_at
`

type CreateCommentParams struct {
	SubmissionID uuid.UUID `json:"submission_id"`
	UserID       uuid.UUID `json:"user_id"`
	UserName     string    `json:"user_name"`
	CommentText  string    `json:"comment_text"`
	IsInternal   bool      `json:"is_internal"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, CreateComment,
		arg.SubmissionID,
		arg.UserID,
		arg.UserName,
		arg.CommentText,
		arg.IsInternal,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.UserID,
		&i.UserName,
		&i.CommentText,
		&i.IsInternal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteComment, id)
	return err
}

const GetCommentByID = `-- name: GetCommentByID :one
SELECT id, submission_id, user_id, user_name, comment_text, is_internal, created_at, updated_at FROM comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, GetCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.UserID,
		&i.UserName,
		&i.CommentText,
		&i.IsInternal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListCommentsBySubmission = `-- name: ListCommentsBySubmission :many
SELECT id, submission_id, user_id, user_name, comment_text, is_internal, created_at, updated_at FROM comments
WHERE submission_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCommentsBySubmission(ctx context.Context, submissionID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, ListCommentsBySubmission, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.UserID,
			&i.UserName,
			&i.CommentText,
			&i.IsInternal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListExternalComments = `-- name: ListExternalComments :many
SELECT id, submission_id, user_id, user_name, comment_text, is_internal, created_at, updated_at FROM comments
WHERE submission_id = $1 AND is_internal = false
ORDER BY created_at ASC
`

func (q *Queries) ListExternalComments(ctx context.Context, submissionID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, ListExternalComments, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.UserID,
			&i.UserName,
			&i.CommentText,
			&i.IsInternal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListInternalComments = `-- name: ListInternalComments :many
SELECT id, submission_id, user_id, user_name, comment_text, is_internal, created_at, updated_at FROM comments
WHERE submission_id = $1 AND is_internal = true
ORDER BY created_at ASC
`

func (q *Queries) ListInternalComments(ctx context.Context, submissionID uuid.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, ListInternalComments, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.UserID,
			&i.UserName,
			&i.CommentText,
			&i.IsInternal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateComment = `-- name: UpdateComment :one
UPDATE comments
SET comment_text = $2
WHERE id = $1
RETURNING id, submission_id, user_id, user_name, comment_text, is_internal, created_at, updated_at
`

type UpdateCommentParams struct {
	ID          uuid.UUID `json:"id"`
	CommentText string    `json:"comment_text"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, UpdateComment, arg.ID, arg.CommentText)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.SubmissionID,
		&i.UserID,
		&i.UserName,
		&i.CommentText,
		&i.IsInternal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
