// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package clientdb

import (
	"context"
)

// iteratorForBulkAssignQuestions implements pgx.CopyFromSource.
type iteratorForBulkAssignQuestions struct {
	rows                 []BulkAssignQuestionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkAssignQuestions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkAssignQuestions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].QuestionID,
		r.rows[0].AssignedTo,
		r.rows[0].AssignedBy,
		r.rows[0].Notes,
	}, nil
}

func (r iteratorForBulkAssignQuestions) Err() error {
	return nil
}

func (q *Queries) BulkAssignQuestions(ctx context.Context, arg []BulkAssignQuestionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"question_assignments"}, []string{"question_id", "assigned_to", "assigned_by", "notes"}, &iteratorForBulkAssignQuestions{rows: arg})
}

// iteratorForBulkCreateQuestions implements pgx.CopyFromSource.
type iteratorForBulkCreateQuestions struct {
	rows                 []BulkCreateQuestionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateQuestions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateQuestions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AuditID,
		r.rows[0].Section,
		r.rows[0].QuestionNumber,
		r.rows[0].QuestionText,
		r.rows[0].QuestionType,
		r.rows[0].HelpText,
		r.rows[0].IsMandatory,
		r.rows[0].DisplayOrder,
	}, nil
}

func (r iteratorForBulkCreateQuestions) Err() error {
	return nil
}

func (q *Queries) BulkCreateQuestions(ctx context.Context, arg []BulkCreateQuestionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"questions"}, []string{"audit_id", "section", "question_number", "question_text", "question_type", "help_text", "is_mandatory", "display_order"}, &iteratorForBulkCreateQuestions{rows: arg})
}
