// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package clientdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApproveSubmission(ctx context.Context, arg ApproveSubmissionParams) (Submission, error)
	AssignQuestionToUser(ctx context.Context, arg AssignQuestionToUserParams) (QuestionAssignment, error)
	BulkAssignQuestions(ctx context.Context, arg []BulkAssignQuestionsParams) (int64, error)
	BulkCreateQuestions(ctx context.Context, arg []BulkCreateQuestionsParams) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateAudit(ctx context.Context, arg CreateAuditParams) (Audit, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateEvidence(ctx context.Context, arg CreateEvidenceParams) (Evidence, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateQuestionAssignment(ctx context.Context, arg CreateQuestionAssignmentParams) (QuestionAssignment, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	DeleteAudit(ctx context.Context, id uuid.UUID) error
	DeleteComment(ctx context.Context, id uuid.UUID) error
	DeleteOldActivityLogs(ctx context.Context, createdAt pgtype.Timestamptz) error
	DeleteQuestion(ctx context.Context, id uuid.UUID) error
	DeleteQuestionAssignment(ctx context.Context, arg DeleteQuestionAssignmentParams) error
	DeleteReport(ctx context.Context, id uuid.UUID) error
	// Get progress for all audits (frameworks) - for dashboard analytics
	GetAllAuditsProgress(ctx context.Context) ([]GetAllAuditsProgressRow, error)
	GetAuditByID(ctx context.Context, id uuid.UUID) (Audit, error)
	GetAuditProgress(ctx context.Context, id uuid.UUID) (GetAuditProgressRow, error)
	GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error)
	GetEvidenceByID(ctx context.Context, id uuid.UUID) (Evidence, error)
	GetEvidenceStats(ctx context.Context) (GetEvidenceStatsRow, error)
	GetQuestionAssignment(ctx context.Context, arg GetQuestionAssignmentParams) (QuestionAssignment, error)
	GetQuestionByID(ctx context.Context, id uuid.UUID) (Question, error)
	GetQuestionWithSubmission(ctx context.Context, id uuid.UUID) (GetQuestionWithSubmissionRow, error)
	GetRecentActivity(ctx context.Context, limit int32) ([]ActivityLog, error)
	GetReportByAuditID(ctx context.Context, auditID uuid.UUID) (Report, error)
	GetReportByID(ctx context.Context, id uuid.UUID) (Report, error)
	GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error)
	GetSubmissionByQuestionID(ctx context.Context, questionID uuid.UUID) (Submission, error)
	GetSubmissionWithEvidence(ctx context.Context, id uuid.UUID) (GetSubmissionWithEvidenceRow, error)
	HardDeleteEvidence(ctx context.Context, id uuid.UUID) error
	ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error)
	ListActivityLogsByAction(ctx context.Context, arg ListActivityLogsByActionParams) ([]ActivityLog, error)
	ListActivityLogsByEntity(ctx context.Context, arg ListActivityLogsByEntityParams) ([]ActivityLog, error)
	ListActivityLogsByUser(ctx context.Context, arg ListActivityLogsByUserParams) ([]ActivityLog, error)
	ListAssignmentsByQuestion(ctx context.Context, questionID uuid.UUID) ([]QuestionAssignment, error)
	ListAssignmentsByUser(ctx context.Context, assignedTo uuid.UUID) ([]ListAssignmentsByUserRow, error)
	ListAudits(ctx context.Context) ([]Audit, error)
	ListAuditsByStatus(ctx context.Context, status AuditStatusEnum) ([]Audit, error)
	ListCommentsBySubmission(ctx context.Context, submissionID uuid.UUID) ([]Comment, error)
	ListEvidenceBySubmission(ctx context.Context, submissionID uuid.UUID) ([]Evidence, error)
	ListEvidenceByUser(ctx context.Context, uploadedBy uuid.UUID) ([]ListEvidenceByUserRow, error)
	ListExternalComments(ctx context.Context, submissionID uuid.UUID) ([]Comment, error)
	ListInternalComments(ctx context.Context, submissionID uuid.UUID) ([]Comment, error)
	ListPendingReviews(ctx context.Context) ([]ListPendingReviewsRow, error)
	ListQuestionAssignments(ctx context.Context, questionID uuid.UUID) ([]QuestionAssignment, error)
	ListQuestionsByAudit(ctx context.Context, auditID uuid.UUID) ([]Question, error)
	ListQuestionsBySection(ctx context.Context, arg ListQuestionsBySectionParams) ([]Question, error)
	// Get questions for a specific user based on their role
	// POC users see all questions, stakeholders see only assigned questions
	ListQuestionsForUser(ctx context.Context, arg ListQuestionsForUserParams) ([]ListQuestionsForUserRow, error)
	ListQuestionsWithSubmissions(ctx context.Context, auditID uuid.UUID) ([]ListQuestionsWithSubmissionsRow, error)
	ListReportsByStatus(ctx context.Context, status ReportStatusEnum) ([]ListReportsByStatusRow, error)
	ListSubmissionsByStatus(ctx context.Context, status SubmissionStatusEnum) ([]ListSubmissionsByStatusRow, error)
	ListSubmissionsByUser(ctx context.Context, submittedBy uuid.UUID) ([]ListSubmissionsByUserRow, error)
	ListUserAssignments(ctx context.Context, assignedTo uuid.UUID) ([]ListUserAssignmentsRow, error)
	MarkReportDelivered(ctx context.Context, id uuid.UUID) (Report, error)
	ReferSubmission(ctx context.Context, arg ReferSubmissionParams) (Submission, error)
	RejectSubmission(ctx context.Context, arg RejectSubmissionParams) (Submission, error)
	ResubmitSubmission(ctx context.Context, arg ResubmitSubmissionParams) (Submission, error)
	SoftDeleteEvidence(ctx context.Context, arg SoftDeleteEvidenceParams) (Evidence, error)
	SubmitSubmission(ctx context.Context, id uuid.UUID) (Submission, error)
	UnassignQuestionFromUser(ctx context.Context, arg UnassignQuestionFromUserParams) error
	UpdateAuditAssignee(ctx context.Context, arg UpdateAuditAssigneeParams) (Audit, error)
	UpdateAuditStatus(ctx context.Context, arg UpdateAuditStatusParams) (Audit, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateReportSigned(ctx context.Context, arg UpdateReportSignedParams) (Report, error)
	UpdateReportUnsigned(ctx context.Context, arg UpdateReportUnsignedParams) (Report, error)
	UpdateSubmissionAnswer(ctx context.Context, arg UpdateSubmissionAnswerParams) (Submission, error)
}

var _ Querier = (*Queries)(nil)
