// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package clientdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateReport = `-- name: CreateReport :one
INSERT INTO reports (
    audit_id,
    unsigned_file_path,
    generated_by,
    status
) VALUES (
    $1, $2, $3, $4
) RETURNING id, audit_id, unsigned_file_path, signed_file_path, generated_by, generated_at, signed_by, signed_at, status, metadata, created_at, updated_at
`

type CreateReportParams struct {
	AuditID          uuid.UUID        `json:"audit_id"`
	UnsignedFilePath *string          `json:"unsigned_file_path"`
	GeneratedBy      uuid.UUID        `json:"generated_by"`
	Status           ReportStatusEnum `json:"status"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, CreateReport,
		arg.AuditID,
		arg.UnsignedFilePath,
		arg.GeneratedBy,
		arg.Status,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AuditID,
		&i.UnsignedFilePath,
		&i.SignedFilePath,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.SignedBy,
		&i.SignedAt,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteReport = `-- name: DeleteReport :exec
DELETE FROM reports
WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteReport, id)
	return err
}

const GetReportByAuditID = `-- name: GetReportByAuditID :one
SELECT id, audit_id, unsigned_file_path, signed_file_path, generated_by, generated_at, signed_by, signed_at, status, metadata, created_at, updated_at FROM reports
WHERE audit_id = $1
`

func (q *Queries) GetReportByAuditID(ctx context.Context, auditID uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, GetReportByAuditID, auditID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AuditID,
		&i.UnsignedFilePath,
		&i.SignedFilePath,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.SignedBy,
		&i.SignedAt,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetReportByID = `-- name: GetReportByID :one
SELECT id, audit_id, unsigned_file_path, signed_file_path, generated_by, generated_at, signed_by, signed_at, status, metadata, created_at, updated_at FROM reports
WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, GetReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AuditID,
		&i.UnsignedFilePath,
		&i.SignedFilePath,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.SignedBy,
		&i.SignedAt,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListReportsByStatus = `-- name: ListReportsByStatus :many
SELECT 
    r.id, r.audit_id, r.unsigned_file_path, r.signed_file_path, r.generated_by, r.generated_at, r.signed_by, r.signed_at, r.status, r.metadata, r.created_at, r.updated_at,
    a.framework_name,
    a.status as audit_status
FROM reports r
JOIN audits a ON a.id = r.audit_id
WHERE r.status = $1
ORDER BY r.generated_at DESC
`

type ListReportsByStatusRow struct {
	ID               uuid.UUID          `json:"id"`
	AuditID          uuid.UUID          `json:"audit_id"`
	UnsignedFilePath *string            `json:"unsigned_file_path"`
	SignedFilePath   *string            `json:"signed_file_path"`
	GeneratedBy      uuid.UUID          `json:"generated_by"`
	GeneratedAt      pgtype.Timestamptz `json:"generated_at"`
	SignedBy         pgtype.UUID        `json:"signed_by"`
	SignedAt         pgtype.Timestamptz `json:"signed_at"`
	Status           ReportStatusEnum   `json:"status"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FrameworkName    string             `json:"framework_name"`
	AuditStatus      AuditStatusEnum    `json:"audit_status"`
}

func (q *Queries) ListReportsByStatus(ctx context.Context, status ReportStatusEnum) ([]ListReportsByStatusRow, error) {
	rows, err := q.db.Query(ctx, ListReportsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportsByStatusRow{}
	for rows.Next() {
		var i ListReportsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.AuditID,
			&i.UnsignedFilePath,
			&i.SignedFilePath,
			&i.GeneratedBy,
			&i.GeneratedAt,
			&i.SignedBy,
			&i.SignedAt,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FrameworkName,
			&i.AuditStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkReportDelivered = `-- name: MarkReportDelivered :one
UPDATE reports
SET status = 'delivered'
WHERE id = $1
RETURNING id, audit_id, unsigned_file_path, signed_file_path, generated_by, generated_at, signed_by, signed_at, status, metadata, created_at, updated_at
`

func (q *Queries) MarkReportDelivered(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, MarkReportDelivered, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AuditID,
		&i.UnsignedFilePath,
		&i.SignedFilePath,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.SignedBy,
		&i.SignedAt,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateReportSigned = `-- name: UpdateReportSigned :one
UPDATE reports
SET 
    signed_file_path = $2,
    signed_by = $3,
    signed_at = NOW(),
    status = 'signed'
WHERE id = $1
RETURNING id, audit_id, unsigned_file_path, signed_file_path, generated_by, generated_at, signed_by, signed_at, status, metadata, created_at, updated_at
`

type UpdateReportSignedParams struct {
	ID             uuid.UUID   `json:"id"`
	SignedFilePath *string     `json:"signed_file_path"`
	SignedBy       pgtype.UUID `json:"signed_by"`
}

func (q *Queries) UpdateReportSigned(ctx context.Context, arg UpdateReportSignedParams) (Report, error) {
	row := q.db.QueryRow(ctx, UpdateReportSigned, arg.ID, arg.SignedFilePath, arg.SignedBy)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AuditID,
		&i.UnsignedFilePath,
		&i.SignedFilePath,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.SignedBy,
		&i.SignedAt,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateReportUnsigned = `-- name: UpdateReportUnsigned :one
UPDATE reports
SET 
    unsigned_file_path = $2,
    status = 'generated'
WHERE id = $1
RETURNING id, audit_id, unsigned_file_path, signed_file_path, generated_by, generated_at, signed_by, signed_at, status, metadata, created_at, updated_at
`

type UpdateReportUnsignedParams struct {
	ID               uuid.UUID `json:"id"`
	UnsignedFilePath *string   `json:"unsigned_file_path"`
}

func (q *Queries) UpdateReportUnsigned(ctx context.Context, arg UpdateReportUnsignedParams) (Report, error) {
	row := q.db.QueryRow(ctx, UpdateReportUnsigned, arg.ID, arg.UnsignedFilePath)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.AuditID,
		&i.UnsignedFilePath,
		&i.SignedFilePath,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.SignedBy,
		&i.SignedAt,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
