// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_databases.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const CreateClientDatabase = `-- name: CreateClientDatabase :one
INSERT INTO client_databases (client_id, db_name, db_host, db_port, db_user, encrypted_password)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, client_id, db_name, db_host, db_port, db_user, encrypted_password, created_at
`

type CreateClientDatabaseParams struct {
	ClientID          uuid.UUID `json:"client_id"`
	DbName            string    `json:"db_name"`
	DbHost            string    `json:"db_host"`
	DbPort            int32     `json:"db_port"`
	DbUser            string    `json:"db_user"`
	EncryptedPassword string    `json:"encrypted_password"`
}

func (q *Queries) CreateClientDatabase(ctx context.Context, arg CreateClientDatabaseParams) (ClientDatabase, error) {
	row := q.db.QueryRow(ctx, CreateClientDatabase,
		arg.ClientID,
		arg.DbName,
		arg.DbHost,
		arg.DbPort,
		arg.DbUser,
		arg.EncryptedPassword,
	)
	var i ClientDatabase
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DbName,
		&i.DbHost,
		&i.DbPort,
		&i.DbUser,
		&i.EncryptedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteClientDatabase = `-- name: DeleteClientDatabase :exec
DELETE FROM client_databases
WHERE client_id = $1
`

func (q *Queries) DeleteClientDatabase(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteClientDatabase, clientID)
	return err
}

const GetClientDatabase = `-- name: GetClientDatabase :one
SELECT id, client_id, db_name, db_host, db_port, db_user, encrypted_password, created_at FROM client_databases
WHERE client_id = $1 LIMIT 1
`

func (q *Queries) GetClientDatabase(ctx context.Context, clientID uuid.UUID) (ClientDatabase, error) {
	row := q.db.QueryRow(ctx, GetClientDatabase, clientID)
	var i ClientDatabase
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DbName,
		&i.DbHost,
		&i.DbPort,
		&i.DbUser,
		&i.EncryptedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const GetClientDatabaseByName = `-- name: GetClientDatabaseByName :one
SELECT id, client_id, db_name, db_host, db_port, db_user, encrypted_password, created_at FROM client_databases
WHERE db_name = $1 LIMIT 1
`

func (q *Queries) GetClientDatabaseByName(ctx context.Context, dbName string) (ClientDatabase, error) {
	row := q.db.QueryRow(ctx, GetClientDatabaseByName, dbName)
	var i ClientDatabase
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DbName,
		&i.DbHost,
		&i.DbPort,
		&i.DbUser,
		&i.EncryptedPassword,
		&i.CreatedAt,
	)
	return i, err
}

const ListClientDatabases = `-- name: ListClientDatabases :many
SELECT id, client_id, db_name, db_host, db_port, db_user, encrypted_password, created_at FROM client_databases
ORDER BY created_at DESC
`

func (q *Queries) ListClientDatabases(ctx context.Context) ([]ClientDatabase, error) {
	rows, err := q.db.Query(ctx, ListClientDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientDatabase{}
	for rows.Next() {
		var i ClientDatabase
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.DbName,
			&i.DbHost,
			&i.DbPort,
			&i.DbUser,
			&i.EncryptedPassword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
