// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"
)

const CountClientBuckets = `-- name: CountClientBuckets :one
SELECT COUNT(*) FROM client_buckets
`

func (q *Queries) CountClientBuckets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountClientBuckets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountClientDatabases = `-- name: CountClientDatabases :one
SELECT COUNT(*) FROM client_databases
`

func (q *Queries) CountClientDatabases(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountClientDatabases)
	var count int64
	err := row.Scan(&count)
	return count, err
}
