// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountClientBuckets(ctx context.Context) (int64, error)
	CountClientDatabases(ctx context.Context) (int64, error)
	CountClients(ctx context.Context) (int64, error)
	CountClientsByStatus(ctx context.Context, status NullClientStatusEnum) (int64, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateClientBucket(ctx context.Context, arg CreateClientBucketParams) (ClientBucket, error)
	CreateClientDatabase(ctx context.Context, arg CreateClientDatabaseParams) (ClientDatabase, error)
	DeleteClient(ctx context.Context, id uuid.UUID) error
	DeleteClientBucket(ctx context.Context, clientID uuid.UUID) error
	DeleteClientDatabase(ctx context.Context, clientID uuid.UUID) error
	GetClient(ctx context.Context, id uuid.UUID) (Client, error)
	GetClientBucket(ctx context.Context, clientID uuid.UUID) (ClientBucket, error)
	GetClientBucketByName(ctx context.Context, bucketName string) (ClientBucket, error)
	GetClientByEmail(ctx context.Context, pocEmail string) (Client, error)
	GetClientDatabase(ctx context.Context, clientID uuid.UUID) (ClientDatabase, error)
	GetClientDatabaseByName(ctx context.Context, dbName string) (ClientDatabase, error)
	ListActiveClients(ctx context.Context) ([]Client, error)
	ListClientBuckets(ctx context.Context) ([]ClientBucket, error)
	ListClientDatabases(ctx context.Context) ([]ClientDatabase, error)
	ListClients(ctx context.Context) ([]Client, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
}

var _ Querier = (*Queries)(nil)
