// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_frameworks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const AssignFrameworkToClient = `-- name: AssignFrameworkToClient :one
INSERT INTO client_frameworks (client_id, framework_id, due_date, status)
VALUES ($1, $2, $3, $4)
RETURNING id, client_id, framework_id, due_date, status, created_at, updated_at
`

type AssignFrameworkToClientParams struct {
	ClientID    uuid.UUID           `json:"client_id"`
	FrameworkID uuid.UUID           `json:"framework_id"`
	DueDate     pgtype.Timestamptz  `json:"due_date"`
	Status      NullAuditStatusEnum `json:"status"`
}

func (q *Queries) AssignFrameworkToClient(ctx context.Context, arg AssignFrameworkToClientParams) (ClientFramework, error) {
	row := q.db.QueryRow(ctx, AssignFrameworkToClient,
		arg.ClientID,
		arg.FrameworkID,
		arg.DueDate,
		arg.Status,
	)
	var i ClientFramework
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FrameworkID,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteClientFramework = `-- name: DeleteClientFramework :exec
DELETE FROM client_frameworks
WHERE id = $1
`

func (q *Queries) DeleteClientFramework(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteClientFramework, id)
	return err
}

const GetClientFramework = `-- name: GetClientFramework :one
SELECT 
    cf.id,
    cf.client_id,
    cf.framework_id,
    cf.due_date,
    cf.status,
    cf.created_at,
    cf.updated_at,
    c.name as client_name,
    f.name as framework_name
FROM client_frameworks cf
JOIN clients c ON cf.client_id = c.id
JOIN compliance_frameworks f ON cf.framework_id = f.id
WHERE cf.id = $1 LIMIT 1
`

type GetClientFrameworkRow struct {
	ID            uuid.UUID           `json:"id"`
	ClientID      uuid.UUID           `json:"client_id"`
	FrameworkID   uuid.UUID           `json:"framework_id"`
	DueDate       pgtype.Timestamptz  `json:"due_date"`
	Status        NullAuditStatusEnum `json:"status"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `json:"updated_at"`
	ClientName    string              `json:"client_name"`
	FrameworkName string              `json:"framework_name"`
}

func (q *Queries) GetClientFramework(ctx context.Context, id uuid.UUID) (GetClientFrameworkRow, error) {
	row := q.db.QueryRow(ctx, GetClientFramework, id)
	var i GetClientFrameworkRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FrameworkID,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientName,
		&i.FrameworkName,
	)
	return i, err
}

const ListClientFrameworks = `-- name: ListClientFrameworks :many
SELECT 
    cf.id,
    cf.client_id,
    cf.framework_id,
    cf.due_date,
    cf.status,
    cf.created_at,
    cf.updated_at,
    c.name as client_name,
    f.name as framework_name
FROM client_frameworks cf
JOIN clients c ON cf.client_id = c.id
JOIN compliance_frameworks f ON cf.framework_id = f.id
WHERE cf.client_id = $1
ORDER BY cf.created_at DESC
`

type ListClientFrameworksRow struct {
	ID            uuid.UUID           `json:"id"`
	ClientID      uuid.UUID           `json:"client_id"`
	FrameworkID   uuid.UUID           `json:"framework_id"`
	DueDate       pgtype.Timestamptz  `json:"due_date"`
	Status        NullAuditStatusEnum `json:"status"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `json:"updated_at"`
	ClientName    string              `json:"client_name"`
	FrameworkName string              `json:"framework_name"`
}

func (q *Queries) ListClientFrameworks(ctx context.Context, clientID uuid.UUID) ([]ListClientFrameworksRow, error) {
	rows, err := q.db.Query(ctx, ListClientFrameworks, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientFrameworksRow{}
	for rows.Next() {
		var i ListClientFrameworksRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.FrameworkID,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientName,
			&i.FrameworkName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListFrameworksByStatus = `-- name: ListFrameworksByStatus :many
SELECT 
    cf.id,
    cf.client_id,
    cf.framework_id,
    cf.due_date,
    cf.status,
    cf.created_at,
    cf.updated_at,
    c.name as client_name,
    f.name as framework_name
FROM client_frameworks cf
JOIN clients c ON cf.client_id = c.id
JOIN compliance_frameworks f ON cf.framework_id = f.id
WHERE cf.status = $1
ORDER BY cf.due_date ASC
`

type ListFrameworksByStatusRow struct {
	ID            uuid.UUID           `json:"id"`
	ClientID      uuid.UUID           `json:"client_id"`
	FrameworkID   uuid.UUID           `json:"framework_id"`
	DueDate       pgtype.Timestamptz  `json:"due_date"`
	Status        NullAuditStatusEnum `json:"status"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz  `json:"updated_at"`
	ClientName    string              `json:"client_name"`
	FrameworkName string              `json:"framework_name"`
}

func (q *Queries) ListFrameworksByStatus(ctx context.Context, status NullAuditStatusEnum) ([]ListFrameworksByStatusRow, error) {
	rows, err := q.db.Query(ctx, ListFrameworksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFrameworksByStatusRow{}
	for rows.Next() {
		var i ListFrameworksByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.FrameworkID,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientName,
			&i.FrameworkName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateClientFrameworkStatus = `-- name: UpdateClientFrameworkStatus :one
UPDATE client_frameworks
SET status = $2
WHERE id = $1
RETURNING id, client_id, framework_id, due_date, status, created_at, updated_at
`

type UpdateClientFrameworkStatusParams struct {
	ID     uuid.UUID           `json:"id"`
	Status NullAuditStatusEnum `json:"status"`
}

func (q *Queries) UpdateClientFrameworkStatus(ctx context.Context, arg UpdateClientFrameworkStatusParams) (ClientFramework, error) {
	row := q.db.QueryRow(ctx, UpdateClientFrameworkStatus, arg.ID, arg.Status)
	var i ClientFramework
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.FrameworkID,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
