// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client_buckets.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const CreateClientBucket = `-- name: CreateClientBucket :one
INSERT INTO client_buckets (client_id, bucket_name)
VALUES ($1, $2)
RETURNING id, client_id, bucket_name, created_at
`

type CreateClientBucketParams struct {
	ClientID   uuid.UUID `json:"client_id"`
	BucketName string    `json:"bucket_name"`
}

func (q *Queries) CreateClientBucket(ctx context.Context, arg CreateClientBucketParams) (ClientBucket, error) {
	row := q.db.QueryRow(ctx, CreateClientBucket, arg.ClientID, arg.BucketName)
	var i ClientBucket
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.BucketName,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteClientBucket = `-- name: DeleteClientBucket :exec
DELETE FROM client_buckets
WHERE client_id = $1
`

func (q *Queries) DeleteClientBucket(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteClientBucket, clientID)
	return err
}

const GetClientBucket = `-- name: GetClientBucket :one
SELECT id, client_id, bucket_name, created_at FROM client_buckets
WHERE client_id = $1 LIMIT 1
`

func (q *Queries) GetClientBucket(ctx context.Context, clientID uuid.UUID) (ClientBucket, error) {
	row := q.db.QueryRow(ctx, GetClientBucket, clientID)
	var i ClientBucket
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.BucketName,
		&i.CreatedAt,
	)
	return i, err
}

const GetClientBucketByName = `-- name: GetClientBucketByName :one
SELECT id, client_id, bucket_name, created_at FROM client_buckets
WHERE bucket_name = $1 LIMIT 1
`

func (q *Queries) GetClientBucketByName(ctx context.Context, bucketName string) (ClientBucket, error) {
	row := q.db.QueryRow(ctx, GetClientBucketByName, bucketName)
	var i ClientBucket
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.BucketName,
		&i.CreatedAt,
	)
	return i, err
}

const ListClientBuckets = `-- name: ListClientBuckets :many
SELECT id, client_id, bucket_name, created_at FROM client_buckets
ORDER BY created_at DESC
`

func (q *Queries) ListClientBuckets(ctx context.Context) ([]ClientBucket, error) {
	rows, err := q.db.Query(ctx, ListClientBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClientBucket{}
	for rows.Next() {
		var i ClientBucket
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.BucketName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
