// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"
)

const CountAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
`

func (q *Queries) CountAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountClientFrameworks = `-- name: CountClientFrameworks :one
SELECT COUNT(*) FROM client_frameworks
`

func (q *Queries) CountClientFrameworks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountClientFrameworks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountFrameworks = `-- name: CountFrameworks :one
SELECT COUNT(*) FROM compliance_frameworks
`

func (q *Queries) CountFrameworks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountFrameworks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountTotalUsers = `-- name: CountTotalUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountTotalUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountTotalUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}
