// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: frameworks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const CreateFramework = `-- name: CreateFramework :one
INSERT INTO compliance_frameworks (name, description, checklist_json, version)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, checklist_json, version, created_at, updated_at
`

type CreateFrameworkParams struct {
	Name          string  `json:"name"`
	Description   *string `json:"description"`
	ChecklistJson []byte  `json:"checklist_json"`
	Version       *string `json:"version"`
}

func (q *Queries) CreateFramework(ctx context.Context, arg CreateFrameworkParams) (ComplianceFramework, error) {
	row := q.db.QueryRow(ctx, CreateFramework,
		arg.Name,
		arg.Description,
		arg.ChecklistJson,
		arg.Version,
	)
	var i ComplianceFramework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ChecklistJson,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteFramework = `-- name: DeleteFramework :exec
DELETE FROM compliance_frameworks
WHERE id = $1
`

func (q *Queries) DeleteFramework(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteFramework, id)
	return err
}

const GetFramework = `-- name: GetFramework :one
SELECT id, name, description, checklist_json, version, created_at, updated_at FROM compliance_frameworks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFramework(ctx context.Context, id uuid.UUID) (ComplianceFramework, error) {
	row := q.db.QueryRow(ctx, GetFramework, id)
	var i ComplianceFramework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ChecklistJson,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetFrameworkByName = `-- name: GetFrameworkByName :one
SELECT id, name, description, checklist_json, version, created_at, updated_at FROM compliance_frameworks
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetFrameworkByName(ctx context.Context, name string) (ComplianceFramework, error) {
	row := q.db.QueryRow(ctx, GetFrameworkByName, name)
	var i ComplianceFramework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ChecklistJson,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListFrameworks = `-- name: ListFrameworks :many
SELECT id, name, description, checklist_json, version, created_at, updated_at FROM compliance_frameworks
ORDER BY created_at DESC
`

func (q *Queries) ListFrameworks(ctx context.Context) ([]ComplianceFramework, error) {
	rows, err := q.db.Query(ctx, ListFrameworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComplianceFramework{}
	for rows.Next() {
		var i ComplianceFramework
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ChecklistJson,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateFramework = `-- name: UpdateFramework :one
UPDATE compliance_frameworks
SET name = $2, description = $3, checklist_json = $4, version = $5
WHERE id = $1
RETURNING id, name, description, checklist_json, version, created_at, updated_at
`

type UpdateFrameworkParams struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Description   *string   `json:"description"`
	ChecklistJson []byte    `json:"checklist_json"`
	Version       *string   `json:"version"`
}

func (q *Queries) UpdateFramework(ctx context.Context, arg UpdateFrameworkParams) (ComplianceFramework, error) {
	row := q.db.QueryRow(ctx, UpdateFramework,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ChecklistJson,
		arg.Version,
	)
	var i ComplianceFramework
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ChecklistJson,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
