// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditStatusEnum string

const (
	AuditStatusEnumPending    AuditStatusEnum = "pending"
	AuditStatusEnumInProgress AuditStatusEnum = "in_progress"
	AuditStatusEnumCompleted  AuditStatusEnum = "completed"
	AuditStatusEnumOverdue    AuditStatusEnum = "overdue"
)

func (e *AuditStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditStatusEnum(s)
	case string:
		*e = AuditStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditStatusEnum: %T", src)
	}
	return nil
}

type NullAuditStatusEnum struct {
	AuditStatusEnum AuditStatusEnum `json:"audit_status_enum"`
	Valid           bool            `json:"valid"` // Valid is true if AuditStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AuditStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditStatusEnum), nil
}

func (e AuditStatusEnum) Valid() bool {
	switch e {
	case AuditStatusEnumPending,
		AuditStatusEnumInProgress,
		AuditStatusEnumCompleted,
		AuditStatusEnumOverdue:
		return true
	}
	return false
}

func AllAuditStatusEnumValues() []AuditStatusEnum {
	return []AuditStatusEnum{
		AuditStatusEnumPending,
		AuditStatusEnumInProgress,
		AuditStatusEnumCompleted,
		AuditStatusEnumOverdue,
	}
}

type ClientStatusEnum string

const (
	ClientStatusEnumActive    ClientStatusEnum = "active"
	ClientStatusEnumInactive  ClientStatusEnum = "inactive"
	ClientStatusEnumSuspended ClientStatusEnum = "suspended"
)

func (e *ClientStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClientStatusEnum(s)
	case string:
		*e = ClientStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ClientStatusEnum: %T", src)
	}
	return nil
}

type NullClientStatusEnum struct {
	ClientStatusEnum ClientStatusEnum `json:"client_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if ClientStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClientStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ClientStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClientStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClientStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClientStatusEnum), nil
}

func (e ClientStatusEnum) Valid() bool {
	switch e {
	case ClientStatusEnumActive,
		ClientStatusEnumInactive,
		ClientStatusEnumSuspended:
		return true
	}
	return false
}

func AllClientStatusEnumValues() []ClientStatusEnum {
	return []ClientStatusEnum{
		ClientStatusEnumActive,
		ClientStatusEnumInactive,
		ClientStatusEnumSuspended,
	}
}

type UserRoleEnum string

const (
	UserRoleEnumNishajAdmin UserRoleEnum = "nishaj_admin"
	UserRoleEnumAuditor     UserRoleEnum = "auditor"
	UserRoleEnumTeamMember  UserRoleEnum = "team_member"
	UserRoleEnumPocInternal UserRoleEnum = "poc_internal"
	UserRoleEnumPocClient   UserRoleEnum = "poc_client"
	UserRoleEnumStakeholder UserRoleEnum = "stakeholder"
)

func (e *UserRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoleEnum(s)
	case string:
		*e = UserRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoleEnum: %T", src)
	}
	return nil
}

type NullUserRoleEnum struct {
	UserRoleEnum UserRoleEnum `json:"user_role_enum"`
	Valid        bool         `json:"valid"` // Valid is true if UserRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoleEnum), nil
}

func (e UserRoleEnum) Valid() bool {
	switch e {
	case UserRoleEnumNishajAdmin,
		UserRoleEnumAuditor,
		UserRoleEnumTeamMember,
		UserRoleEnumPocInternal,
		UserRoleEnumPocClient,
		UserRoleEnumStakeholder:
		return true
	}
	return false
}

func AllUserRoleEnumValues() []UserRoleEnum {
	return []UserRoleEnum{
		UserRoleEnumNishajAdmin,
		UserRoleEnumAuditor,
		UserRoleEnumTeamMember,
		UserRoleEnumPocInternal,
		UserRoleEnumPocClient,
		UserRoleEnumStakeholder,
	}
}

type AuditCycle struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	Status      *string            `json:"status"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditCycleClient struct {
	ID           uuid.UUID          `json:"id"`
	AuditCycleID uuid.UUID          `json:"audit_cycle_id"`
	ClientID     uuid.UUID          `json:"client_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuditCycleFramework struct {
	ID                 uuid.UUID          `json:"id"`
	AuditCycleClientID uuid.UUID          `json:"audit_cycle_client_id"`
	FrameworkID        uuid.UUID          `json:"framework_id"`
	FrameworkName      string             `json:"framework_name"`
	AssignedBy         pgtype.UUID        `json:"assigned_by"`
	AssignedAt         pgtype.Timestamptz `json:"assigned_at"`
	DueDate            pgtype.Date        `json:"due_date"`
	Status             *string            `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	// The auditor assigned to review this framework for the client
	AuditorID pgtype.UUID `json:"auditor_id"`
}

type AuditLog struct {
	ID           uuid.UUID          `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ClientID     pgtype.UUID        `json:"client_id"`
	Action       string             `json:"action"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Client struct {
	ID        uuid.UUID            `json:"id"`
	Name      string               `json:"name"`
	PocEmail  string               `json:"poc_email"`
	Status    NullClientStatusEnum `json:"status"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt pgtype.Timestamptz   `json:"updated_at"`
	// Allowed email domain for client users (e.g., bagaria.com). Only users with emails ending in @<email_domain> can access this client.
	EmailDomain *string `json:"email_domain"`
}

type ClientBucket struct {
	ID         uuid.UUID          `json:"id"`
	ClientID   uuid.UUID          `json:"client_id"`
	BucketName string             `json:"bucket_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ClientDatabase struct {
	ID                uuid.UUID          `json:"id"`
	ClientID          uuid.UUID          `json:"client_id"`
	DbName            string             `json:"db_name"`
	DbHost            string             `json:"db_host"`
	DbPort            int32              `json:"db_port"`
	DbUser            string             `json:"db_user"`
	EncryptedPassword string             `json:"encrypted_password"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ClientFramework struct {
	ID          uuid.UUID           `json:"id"`
	ClientID    uuid.UUID           `json:"client_id"`
	FrameworkID uuid.UUID           `json:"framework_id"`
	DueDate     pgtype.Timestamptz  `json:"due_date"`
	Status      NullAuditStatusEnum `json:"status"`
	CreatedAt   pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz  `json:"updated_at"`
}

type Permission struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Resource    string             `json:"resource"`
	Action      string             `json:"action"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	OidcProvider string             `json:"oidc_provider"`
	OidcSub      string             `json:"oidc_sub"`
	Designation  string             `json:"designation"`
	ClientID     pgtype.UUID        `json:"client_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
