// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignFrameworkToClient(ctx context.Context, arg AssignFrameworkToClientParams) (ClientFramework, error)
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountClientFrameworks(ctx context.Context) (int64, error)
	CountClients(ctx context.Context) (int64, error)
	CountClientsByStatus(ctx context.Context, status NullClientStatusEnum) (int64, error)
	CountFrameworks(ctx context.Context) (int64, error)
	CountTotalUsers(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateClientBucket(ctx context.Context, arg CreateClientBucketParams) (ClientBucket, error)
	CreateClientDatabase(ctx context.Context, arg CreateClientDatabaseParams) (ClientDatabase, error)
	CreateFramework(ctx context.Context, arg CreateFrameworkParams) (ComplianceFramework, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteClient(ctx context.Context, id uuid.UUID) error
	DeleteClientBucket(ctx context.Context, clientID uuid.UUID) error
	DeleteClientDatabase(ctx context.Context, clientID uuid.UUID) error
	DeleteClientFramework(ctx context.Context, id uuid.UUID) error
	DeleteFramework(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAuditLog(ctx context.Context, id uuid.UUID) (AuditLog, error)
	GetClient(ctx context.Context, id uuid.UUID) (Client, error)
	GetClientBucket(ctx context.Context, clientID uuid.UUID) (ClientBucket, error)
	GetClientBucketByName(ctx context.Context, bucketName string) (ClientBucket, error)
	GetClientByEmail(ctx context.Context, pocEmail string) (Client, error)
	GetClientByEmailDomain(ctx context.Context, emailDomain *string) (Client, error)
	GetClientDatabase(ctx context.Context, clientID uuid.UUID) (ClientDatabase, error)
	GetClientDatabaseByName(ctx context.Context, dbName string) (ClientDatabase, error)
	GetClientFramework(ctx context.Context, id uuid.UUID) (GetClientFrameworkRow, error)
	GetFramework(ctx context.Context, id uuid.UUID) (ComplianceFramework, error)
	GetFrameworkByName(ctx context.Context, name string) (ComplianceFramework, error)
	GetPermission(ctx context.Context, id uuid.UUID) (Permission, error)
	GetPermissionByName(ctx context.Context, name string) (Permission, error)
	GetRole(ctx context.Context, id uuid.UUID) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]Permission, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (User, error)
	GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]Permission, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error)
	ListActiveClients(ctx context.Context) ([]Client, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByClient(ctx context.Context, arg ListAuditLogsByClientParams) ([]AuditLog, error)
	ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListClientBuckets(ctx context.Context) ([]ClientBucket, error)
	ListClientDatabases(ctx context.Context) ([]ClientDatabase, error)
	ListClientFrameworks(ctx context.Context, clientID uuid.UUID) ([]ListClientFrameworksRow, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListFrameworks(ctx context.Context) ([]ComplianceFramework, error)
	ListFrameworksByStatus(ctx context.Context, status NullAuditStatusEnum) ([]ListFrameworksByStatusRow, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByClient(ctx context.Context, clientID pgtype.UUID) ([]User, error)
	ListUsersByRole(ctx context.Context, role UserRoleEnum) ([]User, error)
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateClientFrameworkStatus(ctx context.Context, arg UpdateClientFrameworkStatusParams) (ClientFramework, error)
	UpdateFramework(ctx context.Context, arg UpdateFrameworkParams) (ComplianceFramework, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
