// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (email, name, oidc_provider, oidc_sub, designation, client_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, name, oidc_provider, oidc_sub, designation, client_id, created_at, updated_at, last_login
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	OidcProvider string      `json:"oidc_provider"`
	OidcSub      string      `json:"oidc_sub"`
	Designation  string      `json:"designation"`
	ClientID     pgtype.UUID `json:"client_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.Email,
		arg.Name,
		arg.OidcProvider,
		arg.OidcSub,
		arg.Designation,
		arg.ClientID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OidcProvider,
		&i.OidcSub,
		&i.Designation,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteUser, id)
	return err
}

const GetUser = `-- name: GetUser :one
SELECT id, email, name, oidc_provider, oidc_sub, designation, client_id, created_at, updated_at, last_login FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, GetUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OidcProvider,
		&i.OidcSub,
		&i.Designation,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, oidc_provider, oidc_sub, designation, client_id, created_at, updated_at, last_login FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OidcProvider,
		&i.OidcSub,
		&i.Designation,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const GetUserByOIDC = `-- name: GetUserByOIDC :one
SELECT id, email, name, oidc_provider, oidc_sub, designation, client_id, created_at, updated_at, last_login FROM users
WHERE oidc_provider = $1 AND oidc_sub = $2 LIMIT 1
`

type GetUserByOIDCParams struct {
	OidcProvider string `json:"oidc_provider"`
	OidcSub      string `json:"oidc_sub"`
}

func (q *Queries) GetUserByOIDC(ctx context.Context, arg GetUserByOIDCParams) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByOIDC, arg.OidcProvider, arg.OidcSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OidcProvider,
		&i.OidcSub,
		&i.Designation,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const ListTenantUsers = `-- name: ListTenantUsers :many
SELECT id, email, name, oidc_provider, oidc_sub, designation, client_id, created_at, updated_at, last_login FROM users
WHERE client_id IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTenantUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, ListTenantUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.OidcProvider,
			&i.OidcSub,
			&i.Designation,
			&i.ClientID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUsers = `-- name: ListUsers :many
SELECT id, email, name, oidc_provider, oidc_sub, designation, client_id, created_at, updated_at, last_login FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, ListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.OidcProvider,
			&i.OidcSub,
			&i.Designation,
			&i.ClientID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUsersByClient = `-- name: ListUsersByClient :many
SELECT id, email, name, oidc_provider, oidc_sub, designation, client_id, created_at, updated_at, last_login FROM users
WHERE client_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsersByClient(ctx context.Context, clientID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, ListUsersByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.OidcProvider,
			&i.OidcSub,
			&i.Designation,
			&i.ClientID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUsersByRole = `-- name: ListUsersByRole :many
SELECT id, email, name, oidc_provider, oidc_sub, designation, client_id, created_at, updated_at, last_login FROM users
WHERE designation = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsersByRole(ctx context.Context, designation string) ([]User, error) {
	rows, err := q.db.Query(ctx, ListUsersByRole, designation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.OidcProvider,
			&i.OidcSub,
			&i.Designation,
			&i.ClientID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, email = $3, designation = $4
WHERE id = $1
RETURNING id, email, name, oidc_provider, oidc_sub, designation, client_id, created_at, updated_at, last_login
`

type UpdateUserParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Email       string    `json:"email"`
	Designation string    `json:"designation"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, UpdateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Designation,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OidcProvider,
		&i.OidcSub,
		&i.Designation,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return i, err
}

const UpdateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, UpdateUserLastLogin, id)
	return err
}
